# Generated by Django 5.2 on 2025-08-28 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_emailverification_email_alter_emailverification_user'),
        ('clients', '0009_clientcolumn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.TextField(help_text='전송된 메시지 템플릿')),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='발송 대상자 수')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('sending', '발송중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='실제 발송된 건수')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='실패한 건수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='발송 시작 시간', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='발송 완료 시간', null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='accounts.gallery')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS 메시지',
                'verbose_name_plural': 'SMS 메시지들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='발송된 전화번호', max_length=20)),
                ('personalized_message', models.TextField(help_text='개인화된 메시지 내용')),
                ('twilio_sid', models.CharField(blank=True, help_text='Twilio 메시지 SID', max_length=100, null=True)),
                ('twilio_status', models.CharField(blank=True, help_text='Twilio 상태', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('queued', '발송대기'), ('sent', '발송완료'), ('delivered', '전달완료'), ('failed', '실패'), ('undelivered', '전달실패')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='오류 메시지', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='실제 발송 시간', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='전달 확인 시간', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_deliveries', to='clients.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sms.smsmessage')),
            ],
            options={
                'verbose_name': 'SMS 발송 기록',
                'verbose_name_plural': 'SMS 발송 기록들',
                'ordering': ['-created_at'],
            },
        ),
    ]
