# Generated by Django 5.2 on 2025-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist',
            new_name='artist_en',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='dimensions',
            new_name='artist_ko',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='artwork',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title_ko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
