# Generated by Django 5.2 on 2025-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_rename_artist_artwork_artist_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='size',
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size_unit',
            field=models.CharField(blank=True, default='cm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
