# Generated by Django 5.2 on 2025-08-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_gallery_username_and_more'),
        ('artworks', '0003_remove_artwork_size_artwork_depth_artwork_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='accounts.gallery', verbose_name='소속 갤러리'),
        ),
    ]
