# Generated by Django 5.2 on 2025-05-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('buy_artist', models.CharField(max_length=50)),
                ('favorite_artist', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('last_visit', models.DateTimeField()),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('has_missing_fields', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ManyToManyField(blank=True, to='api.clientstatus'),
        ),
    ]
