# Generated by Django 5.2 on 2025-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artwork_artist_alter_artwork_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
