# Generated by Django 5.2 on 2025-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_artwork_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('accessor', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
