# Generated by Django 5.2 on 2025-07-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientcolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.DeleteModel(
            name='ClientColumn',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientStatus',
        ),
    ]
