# Generated by Django 5.2 on 2025-08-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverification_email_alter_emailverification_user'),
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcolumn',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gallery'),
        ),
        migrations.AlterField(
            model_name='clientcolumn',
            name='accessor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='clientcolumn',
            unique_together={('gallery', 'accessor')},
        ),
    ]
