# Generated by Django 5.2 on 2025-08-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_clientcolumn_gallery_alter_clientcolumn_accessor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientColumn',
        ),
    ]
