# Generated by Django 5.2 on 2025-07-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tags',
        ),
    ]
