# Generated by Django 5.2 on 2025-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='태그'),
        ),
    ]
