# Generated by Django 5.2 on 2025-07-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그들',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='tags',
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, to='clients.tag', verbose_name='태그'),
        ),
    ]
