# Generated by Django 5.2 on 2025-08-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_gallery_username_and_more'),
        ('clients', '0007_tag_remove_client_tags_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.gallery', verbose_name='소속 갤러리'),
        ),
        migrations.AddField(
            model_name='tag',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.gallery', verbose_name='소속 갤러리'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='태그명'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('gallery', 'name')},
        ),
    ]
