# Generated by Django 5.2 on 2025-08-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverification_email_alter_emailverification_user'),
        ('clients', '0008_client_gallery_tag_gallery_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='헤더명')),
                ('accessor', models.CharField(max_length=100, verbose_name='접근자')),
                ('type', models.CharField(default='text', max_length=20, verbose_name='필드 타입')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gallery', verbose_name='소속 갤러리')),
            ],
            options={
                'verbose_name': '고객 컬럼',
                'verbose_name_plural': '고객 컬럼들',
                'ordering': ['order', 'id'],
                'unique_together': {('gallery', 'accessor')},
            },
        ),
    ]
