# Generated by Django 5.2 on 2025-08-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('verification_code', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='만료 시간')),
                ('verified', models.BooleanField(default=False, verbose_name='인증 완료')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도 횟수')),
            ],
            options={
                'verbose_name': '전화번호 인증',
                'verbose_name_plural': '전화번호 인증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='자동 생성 갤러리'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='전화번호 인증 시간'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='signup_method',
            field=models.CharField(choices=[('quick', '간편 가입'), ('code', '코드 가입'), ('invited', '초대 가입')], default='quick', max_length=20, verbose_name='가입 방식'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='인증된 전화번호'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='registration_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='가입 코드'),
        ),
    ]
