# Generated by Django 5.2 on 2025-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification_gallery_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='직책'),
        ),
    ]
