# Generated by Django 5.2 on 2025-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사업자등록번호'),
        ),
    ]
