# Generated by Django 5.2 on 2025-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_unique_together_alter_user_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=True, verbose_name='데이터 내보내기'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_manage_gallery_settings',
            field=models.BooleanField(default=True, verbose_name='갤러리 설정'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=True, verbose_name='사용자 관리'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_send_messages',
            field=models.BooleanField(default=True, verbose_name='메시지 발송'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=True, verbose_name='리포트 조회'),
        ),
    ]
