# Generated by Django 5.2 on 2025-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_can_export_data_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_gallery_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False, verbose_name='데이터 내보내기'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_manage_gallery_settings',
            field=models.BooleanField(default=False, verbose_name='갤러리 설정'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='사용자 관리'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_send_messages',
            field=models.BooleanField(default=False, verbose_name='메시지 발송'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='리포트 조회'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('gallery', 'username')},
        ),
    ]
