# Generated by Django 5.2 on 2025-08-15 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_unique_gallery_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='이메일 인증 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이메일 인증 시간'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='인증 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시간')),
                ('used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 시간')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_em_code_eebfba_idx'), models.Index(fields=['user', '-created_at'], name='accounts_em_user_id_1b4ad5_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_858ceb_idx')],
                'unique_together': {('user', 'code')},
            },
        ),
    ]
