# Generated by Django 5.2 on 2025-08-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
    ]
