# Generated by Django 5.2 on 2025-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverification_email_alter_emailverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_logos/', verbose_name='갤러리 로고'),
        ),
    ]
